# Generated by Django 3.0 on 2019-12-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191206_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('post_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostImage')),
            ],
        ),
    ]
