# Generated by Django 3.0 on 2019-12-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191214_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='postfile',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='published_date',
        ),
    ]
