# Generated by Django 3.0 on 2019-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191214_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postfile',
            name='title',
        ),
        migrations.AddField(
            model_name='postfile',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='postfile',
            name='number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
