# Generated by Django 3.0.3 on 2020-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191214_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('0', 'Tin trung tâm'), ('1', 'Tin trong tỉnh'), ('2', 'Hoàn cảnh cần giúp đỡ'), ('3', 'Thông tin chỉ đạo, điều hành')], default='0', max_length=100),
        ),
    ]
