# Generated by Django 3.0.3 on 2020-02-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_link',
        ),
    ]
