# Generated by Django 3.0.3 on 2020-02-17 07:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='type',
            field=models.CharField(choices=[('0', 'Cải cách hành chính'), ('1', 'Văn bản mới'), ('2', 'Thông báo')], default='0', max_length=100, verbose_name='Loại văn bản'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày khởi tạo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Hình ảnh minh họa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('0', 'Tin trung tâm'), ('1', 'Tin trong tỉnh'), ('2', 'Hoàn cảnh cần giúp đỡ'), ('3', 'Thông tin chỉ đạo, điều hành')], default='0', max_length=100, verbose_name='Loại bài đăng'),
        ),
    ]
