# Generated by Django 3.0.3 on 2020-02-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200217_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='type',
            field=models.CharField(choices=[('0', 'Cải cách hành chính'), ('1', 'Thông báo')], default='0', max_length=100, verbose_name='Loại văn bản'),
        ),
    ]
